name: Build and Push to ECR

on:
  push:
    branches:
      - task5  # Trigger the workflow on pushes to the main branch
      
permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Ensure the region is set here

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ap-south-1  # Ensure the region is set here
          

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL }}:${{ github.sha }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}
