name: CI - Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image to Amazon ECR
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Build the Docker image
          docker build -t 864899875002.dkr.ecr.ap-south-1.amazonaws.com/strapi-app-repo:latest .
          
          # Push the Docker image to ECR
          docker push 864899875002.dkr.ecr.ap-south-1.amazonaws.com/strapi-app-repo:latest
