name: Deploy to ECS

on:
  workflow_run:
    workflows: ["CI - Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to ECS Fargate
        run: |
          # Update the ECS service
          ecs-cli compose --project-name strapi-app service up --create-log-groups --cluster strapi-app-cluster
