name: Terraform CI/CD

on:
  workflow_run:
    workflows: ["CI - Build and Push to ECR"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG from commit SHA
        run: echo "IMAGE_TAG=strapi-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Destroy (optional)
        run: terraform destroy -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="image_tag=${{ env.IMAGE_TAG }}"
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/
